version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped
