version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - .env
