version: "3"
services:
  backend:
    build: Dockerfile.backend
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    env_file:
      - .env
  fontend:
    build: Dockerfile.frontend
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - .env
